<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXlnudjs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXlnudjs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXlnudjs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXlnudjs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXlnudjs\appProdProjectContainer([
    'container.build_hash' => 'Xlnudjs',
    'container.build_id' => 'abef0253',
    'container.build_time' => 1604600554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXlnudjs');
